"""Generate populated context documents from the sprint YAML.

Story 153-6: sm-setup (and, in a follow-up, the gate recovery pipeline) need a
deterministic, non-interactive way to produce
``sprint/context/context-{type}-{id}.md`` so the ``tea-context`` entry gate and
the ``sm-setup-exit`` story-context check pass on a real artifact rather than
the SM-Assessment escape hatch. This is the non-interactive backing for the
interactive ``/pf-context create`` skill (SOUL #11: automatic beats
instructional).

Functions return result dicts (SOUL #10): ``{"success": bool, "path"?: str,
"error"?: str}`` — callers decide what a failure means.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from pf.common.config import get_project_root
from pf.sprint.loader import find_epic, get_story_by_id, load_sprint

# Story / epic IDs are flat tokens (e.g. "153-6", "153"). Reject anything that
# could escape sprint/context/ via path interpolation when we build the output
# filename (mirrors `_CONTEXT_ID_RE` in pf.validate.cli — same threat).
_CONTEXT_ID_RE = re.compile(r"\A[A-Za-z0-9_-]+\Z")


def _render_acceptance_criteria(acs: Any) -> str:
    """Render an acceptance-criteria list, degrading gracefully when absent.

    Real shard stories frequently carry no ``acceptance_criteria`` key, so the
    generator must still emit a valid (non-empty) section.
    """
    if not acs:
        return (
            "_No acceptance criteria recorded in the sprint YAML — "
            "TEA to define during the RED phase._"
        )
    if isinstance(acs, str):
        acs = [acs]
    return "\n".join(f"- {item}" for item in acs)


def _render_story_context(story: dict, epic: dict | None) -> str:
    sid = story.get("id", "")
    title = story.get("title", "(untitled)")
    stype = story.get("type", "story")
    points = story.get("points", "")
    priority = story.get("priority", "")
    workflow = story.get("workflow", "")
    repos = story.get("repos", "")
    description = story.get("description", "")
    epic_title = (epic or {}).get("title", "")

    problem = description or (
        "_No description in the sprint YAML — see the story title above and "
        "the epic context for scope._"
    )

    return f"""# Story {sid} Context

## Title
{title}

## Metadata
- **Story ID:** {sid}
- **Type:** {stype}
- **Points:** {points}
- **Priority:** {priority}
- **Workflow:** {workflow}
- **Repo:** {repos}
- **Epic:** {epic_title}

## Problem
{problem}

## Technical Approach
_Approach hints to be refined by TEA/Dev. The story title above defines the
intended behavior._

## Scope
- In scope: the behavior described by the story title.
- Out of scope: unrelated changes.

## Acceptance Criteria
{_render_acceptance_criteria(story.get("acceptance_criteria"))}

---
_Generated by `pf context create story {sid}` from the sprint YAML._
"""


def _render_epic_context(epic: dict) -> str:
    eid = epic.get("id", "")
    title = epic.get("title", "(untitled)")
    description = epic.get("description", "")
    repos = epic.get("repos", "")

    return f"""# Epic {eid} Context

## Title
{title}

## Overview
{description or "_No description recorded in the sprint YAML._"}

## Metadata
- **Epic ID:** {eid}
- **Repo:** {repos}

## Background
_Cross-story constraints and guardrails to be filled in as the epic
progresses._

---
_Generated by `pf context create epic {eid}` from the sprint YAML._
"""


def generate_context(
    context_type: str,
    target_id: str,
    project_root: Path | None = None,
) -> dict:
    """Generate ``sprint/context/context-{type}-{id}.md`` from the sprint YAML.

    Args:
        context_type: "story" or "epic".
        target_id: Story ID (e.g. "153-6") or epic ID (e.g. "153").
        project_root: Override the project root (defaults to auto-detect).

    Returns:
        ``{"success": True, "path": str}`` on success, otherwise
        ``{"success": False, "error": str}``.
    """
    if context_type not in ("story", "epic"):
        return {"success": False, "error": f"Unknown context type: {context_type!r}"}

    if not _CONTEXT_ID_RE.match(target_id):
        return {
            "success": False,
            "error": (
                f"Invalid {context_type} id: {target_id!r} — must contain only "
                "letters, digits, dashes, and underscores."
            ),
        }

    root = project_root or get_project_root()
    sprint_data = load_sprint(root)

    if context_type == "story":
        story = get_story_by_id(target_id)
        if not story:
            return {
                "success": False,
                "error": f"Story {target_id} not found in the sprint.",
            }
        epic_num = target_id.split("-")[0]
        epic = find_epic(sprint_data, epic_num) if sprint_data else None
        content = _render_story_context(story, epic)
    else:
        epic = find_epic(sprint_data, target_id) if sprint_data else None
        if not epic:
            return {
                "success": False,
                "error": f"Epic {target_id} not found in the sprint.",
            }
        content = _render_epic_context(epic)

    out_dir = Path(root) / "sprint" / "context"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"context-{context_type}-{target_id}.md"
    out_path.write_text(content, encoding="utf-8")

    return {"success": True, "path": str(out_path)}
