#!/usr/bin/env bash
#
# Reference Integrity Checker for Pennyfarthing
# Validates that all cross-file references in markdown files exist
#
# Usage: ./tests/check-references.sh [--verbose]
#
# Exit codes:
#   0 - All references valid
#   1 - Broken references found
#   2 - Script error

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

VERBOSE="${1:-}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Counters
TOTAL_REFS=0
BROKEN_REFS=0
SKIPPED_REFS=0

declare -a BROKEN_LIST=()

log_verbose() {
    if [[ "$VERBOSE" == "--verbose" || "$VERBOSE" == "-v" ]]; then
        echo "$@"
    fi
}

log_error() {
    echo -e "${RED}ERROR:${NC} $*" >&2
}

log_success() {
    echo -e "${GREEN}$*${NC}"
}

log_warning() {
    echo -e "${YELLOW}WARNING:${NC} $*"
}

# Check if a reference should be validated
# Returns 0 if should check, 1 if should skip
should_check_reference() {
    local ref="$1"

    # Skip template/placeholder patterns
    [[ "$ref" =~ \{.*\} ]] && return 1           # {STORY_ID}, {agent}, etc.
    [[ "$ref" =~ \[.*\] ]] && return 1           # [name], [story-id], etc.
    [[ "$ref" =~ \<.*\> ]] && return 1           # <name>, etc.
    [[ "$ref" =~ \$\{.*\} ]] && return 1         # ${VAR}
    [[ "$ref" =~ \$[A-Z_]+ ]] && return 1        # $PROJECT_ROOT, etc.
    [[ "$ref" =~ \.\./ ]] && return 1            # Relative parent refs
    [[ "$ref" =~ \* ]] && return 1               # Glob patterns
    [[ "$ref" == ".claude/agents/[name].md" ]] && return 1
    [[ "$ref" == ".claude/commands/[name].md" ]] && return 1

    # Skip example/documentation patterns
    [[ "$ref" =~ my-theme ]] && return 1              # Example theme name
    [[ "$ref" =~ custom/ ]] && return 1               # Custom personas (optional)

    return 0
}

# Resolve a .claude/ reference to actual path
# When embedded as submodule: .claude/subagents/ -> .claude/pennyfarthing/core/subagents/
# When standalone: .claude/subagents/ -> core/subagents/
resolve_reference() {
    local ref="$1"
    local source_file="$2"

    # Remove leading backticks and quotes
    ref="${ref#\`}"
    ref="${ref%\`}"
    ref="${ref#\"}"
    ref="${ref%\"}"
    ref="${ref#\'}"
    ref="${ref%\'}"

    # For pennyfarthing standalone, .claude/ references map to:
    # .claude/subagents/  -> core/subagents/
    # .claude/agents/     -> core/agents/
    # .claude/guides/       -> core/guides/
    # .claude/skills/     -> skills/
    # .claude/personas/   -> personas/
    # .claude/persona-config.yaml -> persona-config.yaml (project-specific, may not exist)

    local resolved=""

    if [[ "$ref" == .claude/subagents/* ]]; then
        resolved="${PROJECT_ROOT}/core/subagents/${ref#.claude/subagents/}"
    elif [[ "$ref" == .claude/agents/*-sidecar/* ]]; then
        # Sidecar directories are project-specific, skip validation
        echo "SKIP:project-specific"
        return
    elif [[ "$ref" == .claude/agents/* ]]; then
        resolved="${PROJECT_ROOT}/core/agents/${ref#.claude/agents/}"
    elif [[ "$ref" == .claude/guides/shared-context.md ]]; then
        # Project-specific, generated by init-project.sh
        echo "SKIP:project-specific"
        return
    elif [[ "$ref" == .claude/guides/agent-scopes.yaml ]]; then
        # Project-specific, generated by init-project.sh
        echo "SKIP:project-specific"
        return
    elif [[ "$ref" == .claude/guides/* ]]; then
        resolved="${PROJECT_ROOT}/core/guides/${ref#.claude/guides/}"
    elif [[ "$ref" == .claude/skills/* ]]; then
        resolved="${PROJECT_ROOT}/skills/${ref#.claude/skills/}"
    elif [[ "$ref" == .claude/personas/* ]]; then
        resolved="${PROJECT_ROOT}/personas/${ref#.claude/personas/}"
    elif [[ "$ref" == .claude/persona-config.yaml ]]; then
        # Project-specific config, skip
        echo "SKIP:project-specific"
        return
    elif [[ "$ref" == .claude/project/* ]]; then
        # Project-specific paths, skip
        echo "SKIP:project-specific"
        return
    elif [[ "$ref" == .session/* ]]; then
        # Session files are runtime, skip
        echo "SKIP:runtime"
        return
    elif [[ "$ref" == .claude/commands/* ]]; then
        resolved="${PROJECT_ROOT}/core/commands/${ref#.claude/commands/}"
    else
        # Unknown .claude/ reference pattern
        echo "SKIP:unknown-pattern"
        return
    fi

    echo "$resolved"
}

# Check references in a single file
check_file() {
    local file="$1"
    local relative_file="${file#$PROJECT_ROOT/}"

    log_verbose "Checking: $relative_file"

    # Extract .claude/ references from markdown
    # Patterns: `.claude/...`, ".claude/...", .claude/... (unquoted in text)
    local refs
    refs=$(grep -oE '`\.claude/[^`]+`|"\.claude/[^"]+"|\.claude/[a-zA-Z0-9_./-]+\.md|\.claude/[a-zA-Z0-9_./-]+\.yaml' "$file" 2>/dev/null || true)

    while IFS= read -r ref; do
        [[ -z "$ref" ]] && continue

        # Clean up the reference
        ref="${ref#\`}"
        ref="${ref%\`}"
        ref="${ref#\"}"
        ref="${ref%\"}"

        ((TOTAL_REFS++))

        # Check if we should validate this reference
        if ! should_check_reference "$ref"; then
            ((SKIPPED_REFS++))
            log_verbose "  SKIP (template): $ref"
            continue
        fi

        # Resolve the reference
        local resolved
        resolved=$(resolve_reference "$ref" "$file")

        if [[ "$resolved" == SKIP:* ]]; then
            ((SKIPPED_REFS++))
            log_verbose "  SKIP (${resolved#SKIP:}): $ref"
            continue
        fi

        # Check if file exists
        if [[ -f "$resolved" || -d "$resolved" ]]; then
            log_verbose "  OK: $ref -> $resolved"
        else
            ((BROKEN_REFS++))
            BROKEN_LIST+=("$relative_file: $ref -> $resolved")
            log_verbose "  BROKEN: $ref -> $resolved"
        fi

    done <<< "$refs"
}

# Check theme file references
check_theme_references() {
    echo "Checking theme files..."

    local themes_dir="${PROJECT_ROOT}/personas/themes"

    if [[ ! -d "$themes_dir" ]]; then
        log_error "Themes directory not found: $themes_dir"
        return 1
    fi

    # Check that required themes exist
    local required_themes=("discworld.yaml" "star-trek.yaml" "literary-classics.yaml" "minimalist.yaml")

    for theme in "${required_themes[@]}"; do
        ((TOTAL_REFS++))
        if [[ -f "$themes_dir/$theme" ]]; then
            log_verbose "  OK: personas/themes/$theme"
        else
            ((BROKEN_REFS++))
            BROKEN_LIST+=("Required theme missing: personas/themes/$theme")
        fi
    done
}

# Check subagent references consistency
check_subagent_references() {
    echo "Checking subagent references..."

    local subagents_dir="${PROJECT_ROOT}/core/subagents"

    # Get list of all subagent files
    local subagent_files
    subagent_files=$(find "$subagents_dir" -name "*.md" -type f 2>/dev/null)

    # Check that subagents referenced in agent files exist
    local agent_dir="${PROJECT_ROOT}/core/agents"

    for agent_file in "$agent_dir"/*.md; do
        [[ -f "$agent_file" ]] || continue

        # Extract subagent references
        local subagent_refs
        subagent_refs=$(grep -oE 'subagents/[a-z-]+\.md' "$agent_file" 2>/dev/null || true)

        while IFS= read -r ref; do
            [[ -z "$ref" ]] && continue
            ((TOTAL_REFS++))

            local full_path="${PROJECT_ROOT}/core/${ref}"
            if [[ -f "$full_path" ]]; then
                log_verbose "  OK: $ref (from ${agent_file##*/})"
            else
                ((BROKEN_REFS++))
                BROKEN_LIST+=("${agent_file##*/}: subagent not found: $ref")
            fi
        done <<< "$subagent_refs"
    done
}

# Check skill references
check_skill_references() {
    echo "Checking skill references..."

    local skills_dir="${PROJECT_ROOT}/skills"

    if [[ ! -d "$skills_dir" ]]; then
        log_warning "Skills directory not found: $skills_dir"
        return 0
    fi

    # Each skill should have a SKILL.md
    for skill in "$skills_dir"/*/; do
        [[ -d "$skill" ]] || continue
        ((TOTAL_REFS++))

        local skill_name="${skill%/}"
        skill_name="${skill_name##*/}"

        if [[ -f "$skill/SKILL.md" ]]; then
            log_verbose "  OK: skills/$skill_name/SKILL.md"
        else
            ((BROKEN_REFS++))
            BROKEN_LIST+=("Skill missing SKILL.md: skills/$skill_name/")
        fi
    done
}

# Main
main() {
    echo "========================================"
    echo "Pennyfarthing Reference Integrity Check"
    echo "========================================"
    echo ""

    # Check all markdown files in core/
    echo "Checking core/ markdown files..."
    while IFS= read -r -d '' file; do
        check_file "$file"
    done < <(find "${PROJECT_ROOT}/core" -name "*.md" -type f -print0 2>/dev/null)

    echo ""
    check_theme_references

    echo ""
    check_subagent_references

    echo ""
    check_skill_references

    echo ""
    echo "========================================"
    echo "Summary"
    echo "========================================"
    echo "Total references checked: $TOTAL_REFS"
    echo "Skipped (templates/runtime): $SKIPPED_REFS"
    echo "Broken references: $BROKEN_REFS"
    echo ""

    if [[ $BROKEN_REFS -gt 0 ]]; then
        echo -e "${RED}FAILED: $BROKEN_REFS broken reference(s) found${NC}"
        echo ""
        echo "Broken references:"
        for broken in "${BROKEN_LIST[@]}"; do
            echo "  - $broken"
        done
        exit 1
    else
        log_success "PASSED: All references valid"
        exit 0
    fi
}

main "$@"
