"""
Generate usage.md files for skills that wrap CLI command groups.

Introspects live `pf <group> --help` output, parses Click help format,
and renders markdown matching the hand-written usage.md convention.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from pf.common.config import get_dist_root, get_project_root

# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class CommandOption:
    """A CLI option or argument."""

    name: str
    required: bool
    type: str  # "Arg" or "Option"
    description: str


@dataclass
class ParsedCommand:
    """A single CLI command parsed from --help output."""

    name: str
    description: str
    options: list[CommandOption] = field(default_factory=list)


@dataclass
class CommandGroup:
    """A group of commands (possibly nested)."""

    name: str
    prefix: list[str]  # e.g. ["sprint", "story"]
    description: str
    commands: list[ParsedCommand] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Registry loading
# ---------------------------------------------------------------------------


def _load_registries(dist_root: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    """Load skill-registry.yaml and command-registry.yaml."""
    skill_path = dist_root / "skills" / "skill-registry.yaml"
    cmd_path = dist_root / "command-registry.yaml"

    skill_reg = yaml.safe_load(skill_path.read_text())
    cmd_reg = yaml.safe_load(cmd_path.read_text())

    return skill_reg, cmd_reg


def _get_skills_with_commands(
    skill_reg: dict[str, Any],
    cmd_reg: dict[str, Any],
    skill_filter: str | None = None,
) -> list[dict[str, Any]]:
    """Return skills that have a command_group field, with their CLI prefix."""
    results = []
    skills = skill_reg.get("skills", {})
    groups = cmd_reg.get("groups", {})

    for skill_name, skill_data in skills.items():
        if skill_filter and skill_name != skill_filter:
            continue
        if skill_data.get("deprecated"):
            continue

        command_group = skill_data.get("command_group")
        if not command_group:
            continue

        # Look up CLI prefix from command-registry
        group_data = groups.get(command_group, {})
        cli_prefix = group_data.get("cli", "")  # e.g. "pf sprint"

        results.append(
            {
                "skill_name": skill_name,
                "command_group": command_group,
                "cli_prefix": cli_prefix,
                "group_data": group_data,
            }
        )

    return results


# ---------------------------------------------------------------------------
# CLI introspection
# ---------------------------------------------------------------------------


def _run_help(cmd_parts: list[str], timeout: int = 10) -> str | None:
    """Run `pf <parts...> --help` and return stdout, or None on failure."""
    full_cmd = ["pf"] + cmd_parts + ["--help"]
    try:
        result = subprocess.run(
            full_cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        if result.returncode == 0:
            return result.stdout
        return None
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return None


def _discover_subcommands(help_text: str) -> list[str]:
    """Extract subcommand names from Click's auto-generated Commands section.

    Click help may contain multiple "Commands:" blocks — one in the docstring
    (manual) and one auto-generated by Click at the end. We take the last one
    since that's the real Click command listing.
    """
    # Find ALL "Commands:" sections, take the last one
    sections: list[list[str]] = []
    current_section: list[str] | None = None

    for line in help_text.splitlines():
        if re.match(r"^Commands:", line.strip()):
            current_section = []
            continue
        if current_section is not None:
            if not line.strip():
                if current_section:
                    sections.append(current_section)
                    current_section = None
                continue
            current_section.append(line)

    # Capture final section if file doesn't end with blank line
    if current_section:
        sections.append(current_section)

    if not sections:
        return []

    # Use the last Commands section (Click's auto-generated one)
    last_section = sections[-1]
    commands: list[str] = []
    for line in last_section:
        match = re.match(r"^\s+(\S+)", line)
        if match:
            commands.append(match.group(1))

    return commands


def _walk_command_tree(
    prefix: list[str],
    depth: int = 0,
    max_depth: int = 2,
) -> list[CommandGroup]:
    """Recursively discover command groups up to max_depth levels."""
    help_text = _run_help(prefix)
    if not help_text:
        return []

    # Parse the group description (first non-empty line after Usage block)
    group_desc = _extract_group_description(help_text)

    subcommands = _discover_subcommands(help_text)
    if not subcommands:
        return []

    group = CommandGroup(
        name=prefix[-1] if prefix else "root",
        prefix=list(prefix),
        description=group_desc,
    )

    nested_groups: list[CommandGroup] = []

    for subcmd in subcommands:
        sub_help = _run_help(prefix + [subcmd])
        if sub_help is None:
            continue

        # Check if this subcommand is itself a group (has Commands section)
        sub_subcommands = _discover_subcommands(sub_help)
        if sub_subcommands and depth < max_depth:
            # It's a nested group — recurse
            nested = _walk_command_tree(prefix + [subcmd], depth + 1, max_depth)
            nested_groups.extend(nested)
        else:
            # It's a leaf command — parse its help
            parsed = _parse_command_help(subcmd, sub_help)
            group.commands.append(parsed)

    groups = []
    if group.commands:
        groups.append(group)
    groups.extend(nested_groups)

    return groups


def _extract_group_description(help_text: str) -> str:
    """Extract the group description from help text (first paragraph after Usage)."""
    lines = help_text.splitlines()
    desc_lines: list[str] = []
    past_header = False

    for line in lines:
        stripped = line.strip()
        if not past_header:
            # Skip until we're past "Usage:" block and blank lines
            if stripped.startswith("Usage:"):
                past_header = True
            continue
        if not stripped:
            if desc_lines:
                break
            continue
        if stripped.startswith("Options:") or stripped.startswith("Commands:"):
            break
        desc_lines.append(stripped)

    return " ".join(desc_lines)


# ---------------------------------------------------------------------------
# Help text parsing
# ---------------------------------------------------------------------------


def _parse_command_help(name: str, help_text: str) -> ParsedCommand:
    """Parse a Click command's --help output into structured data."""
    description = _extract_group_description(help_text)
    options = _parse_options_and_args(help_text)

    return ParsedCommand(
        name=name,
        description=description,
        options=options,
    )


def _parse_options_and_args(help_text: str) -> list[CommandOption]:
    """Parse Options and Arguments sections from Click help output."""
    options: list[CommandOption] = []

    # Build a description map from the Arguments section (if present)
    arg_descriptions: dict[str, str] = {}
    args_section = _extract_section(help_text, "Arguments")
    if args_section:
        for match in re.finditer(
            r"^\s+(\S+)\s{2,}(.+?)$",
            args_section,
            re.MULTILINE,
        ):
            name = match.group(1)
            desc = match.group(2).strip()
            # Strip leading "- " that Click's formatted help often uses
            desc = re.sub(r"^-\s+", "", desc)
            arg_descriptions[name] = desc

    # Extract positional arguments from the Usage line
    usage_match = re.search(r"^Usage:\s+\S+.*?\[OPTIONS\][ \t]*(.*?)$", help_text, re.MULTILINE)
    if usage_match:
        args_str = usage_match.group(1).strip()
        if args_str:
            # Parse tokens like "NAME", "[NAME]", "<NAME>", "[FILTER]"
            for token in re.findall(r"\[?[A-Z_]+\]?", args_str):
                is_optional = token.startswith("[")
                name = token.strip("[]<>")
                desc = arg_descriptions.get(name, "")
                options.append(
                    CommandOption(
                        name=name,
                        required=not is_optional,
                        type="Arg",
                        description=desc,
                    )
                )

    # Parse Options section (skip --help)
    opts_section = _extract_section(help_text, "Options")
    if opts_section:
        # Match option lines: "  --name TEXT  Description" or "  -s, --name  Description"
        opt_pattern = re.compile(
            r"^\s+(-[\w-]+(?:,\s*-[\w-]+)*)"  # option flags
            r"(?:\s+(\S+))?"  # optional metavar
            r"\s{2,}(.+?)$",  # description
            re.MULTILINE,
        )
        for match in opt_pattern.finditer(opts_section):
            flag = match.group(1).strip()
            desc = match.group(3).strip()

            if "--help" in flag:
                continue

            required = "[required]" in desc.lower()
            options.append(
                CommandOption(
                    name=flag,
                    required=required,
                    type="Option",
                    description=re.sub(r"\s*\[required\]", "", desc, flags=re.IGNORECASE).strip(),
                )
            )

    return options


def _extract_section(help_text: str, section_name: str) -> str | None:
    """Extract a named section from Click help output.

    Handles both top-level sections (e.g. "Options:") and indented
    sections inside docstrings (e.g. "  Arguments:").
    """
    pattern = re.compile(
        rf"^\s*{section_name}:\s*\n((?:(?:  .+|)\n)*)",
        re.MULTILINE,
    )
    match = pattern.search(help_text)
    return match.group(1) if match else None


# ---------------------------------------------------------------------------
# Markdown generation
# ---------------------------------------------------------------------------


def _generate_usage_md(
    skill_name: str,
    cli_prefix: str,
    groups: list[CommandGroup],
) -> str:
    """Render markdown matching existing usage.md format."""
    # Derive a human-friendly title from skill name
    title = skill_name.replace("pf-", "").replace("-", " ").title()

    lines: list[str] = []
    lines.append(f"# {title} CLI — Detailed Usage")
    lines.append("")

    for i, group in enumerate(groups):
        # Section header
        if len(groups) == 1 and group.prefix == cli_prefix.replace("pf ", "").split():
            lines.append("## Commands")
        elif len(group.prefix) > 1:
            subgroup_name = " ".join(group.prefix[1:]).title()
            lines.append(f"## {subgroup_name} Commands")
        else:
            lines.append("## Top-Level Commands")

        lines.append("")

        for cmd in group.commands:
            full_cmd = "pf.sh " + " ".join(group.prefix) + " " + cmd.name
            lines.append(f"### `{full_cmd}`")
            lines.append("")

            if cmd.description:
                lines.append(cmd.description)
                lines.append("")

            if cmd.options:
                lines.append("| Arg/Option | Required | Description |")
                lines.append("|------------|----------|-------------|")
                for opt in cmd.options:
                    req = "Yes" if opt.required else "No"
                    lines.append(f"| `{opt.name}` | {req} | {opt.description} |")
                lines.append("")

        if i < len(groups) - 1:
            lines.append("---")
            lines.append("")

    # Ensure trailing newline
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------


def run_sync_skills(
    dry_run: bool = False,
    skill_filter: str | None = None,
) -> dict[str, Any]:
    """Sync usage.md files for skills with CLI command groups.

    Returns:
        {success: bool, data?: {skills: [...], summary: str}, error?: str}
    """
    try:
        root = get_project_root()
        dist_root = get_dist_root(project_root=root)
    except FileNotFoundError as exc:
        return {"success": False, "error": str(exc)}

    if dist_root is None:
        return {"success": False, "error": "Could not find pennyfarthing-dist directory"}

    try:
        skill_reg, cmd_reg = _load_registries(dist_root)
    except Exception as exc:
        return {"success": False, "error": f"Failed to load registries: {exc}"}

    skill_entries = _get_skills_with_commands(skill_reg, cmd_reg, skill_filter)

    if skill_filter and not skill_entries:
        return {
            "success": False,
            "error": f"Skill '{skill_filter}' not found or has no command_group",
        }

    results: list[dict[str, Any]] = []
    written = 0
    skipped = 0

    for entry in skill_entries:
        skill_name = entry["skill_name"]
        cli_prefix = entry["cli_prefix"]

        if not cli_prefix:
            results.append(
                {
                    "skill": skill_name,
                    "status": "skipped",
                    "reason": "no cli prefix in command-registry",
                }
            )
            skipped += 1
            continue

        # Parse prefix into parts: "pf sprint" -> ["sprint"]
        prefix_parts = cli_prefix.replace("pf ", "").split()

        # Walk the command tree
        groups = _walk_command_tree(prefix_parts)

        if not groups:
            results.append(
                {
                    "skill": skill_name,
                    "status": "skipped",
                    "reason": "no commands discovered (CLI may not be available)",
                }
            )
            skipped += 1
            continue

        total_commands = sum(len(g.commands) for g in groups)
        markdown = _generate_usage_md(skill_name, cli_prefix, groups)

        # Resolve output path
        usage_path = dist_root / "skills" / skill_name / "usage.md"

        if dry_run:
            results.append(
                {
                    "skill": skill_name,
                    "status": "dry_run",
                    "path": str(usage_path.relative_to(root)),
                    "commands": total_commands,
                }
            )
        else:
            usage_path.parent.mkdir(parents=True, exist_ok=True)
            usage_path.write_text(markdown)
            results.append(
                {
                    "skill": skill_name,
                    "status": "written",
                    "path": str(usage_path.relative_to(root)),
                    "commands": total_commands,
                }
            )
            written += 1

    parts = []
    if written:
        parts.append(f"{written} written")
    if skipped:
        parts.append(f"{skipped} skipped")
    if dry_run:
        previewed = len(results) - skipped
        parts.append(f"{previewed} previewed")
    summary = f"Done: {', '.join(parts)}." if parts else "No skills with command groups found."

    return {
        "success": True,
        "data": {
            "skills": results,
            "summary": summary,
        },
    }
