"""Data models for the demo artifact generator pipeline."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class StoryType(Enum):
    """Deterministic story classification types."""

    UI = "ui"
    BACKEND = "backend"
    INFRASTRUCTURE = "infrastructure"
    REFACTOR = "refactor"
    BUGFIX = "bugfix"


class ArtifactType(Enum):
    """Artifact types produced by the demo pipeline."""

    UI_SCREENSHOTS = "ui_screenshots"
    SLIDE_DECK = "slide_deck"
    DEMO_SCRIPT = "demo_script"
    MERMAID_DIAGRAM = "mermaid_diagram"
    NARRATIVE = "narrative"
    BEFORE_AFTER_COMPARISON = "before_after_comparison"
    PROBLEM_STATEMENT = "problem_statement"


@dataclass
class SignalBundle:
    """All signals collected from a completed story."""

    story_id: str
    title: str
    jira_key: str | None
    points: int | None
    acceptance_criteria: list[str]
    pr_diff: str
    commit_messages: list[str]
    session_fields: dict[str, str]
    review_findings: str | None
    file_extensions: set[str] = field(default_factory=set)


@dataclass
class ClassifiedStory:
    """A story classified with its type and artifact list."""

    signals: SignalBundle
    story_type: StoryType
    artifacts: list[ArtifactType]


@dataclass
class GeneratedContent:
    """Content generated by the Generator (145-3) for downstream assembly."""

    problem_statement: str
    what_changed: str
    why_this_approach: str
    before_after: str | None
    demo_script: str
    diagram_source: str | None
    slide_outline: list[dict]
    story_type: StoryType
    story_id: str
